module.exports = {
    user: [
        {
            type: 'autogenerated',
            dirName: 'user',
        }
    ],
    td: [
        {
            type: 'autogenerated',
            dirName: 'td',
        }
    ],
    it: [
        {
            type: 'autogenerated',
            dirName: 'it',
        }
    ]
};
