module.exports = {
    user: [
        {
            type: 'autogenerated',
            dirName: 'user',
        }
    ],
    td: [
        {
            type: 'autogenerated',
            dirName: 'td',
        }
    ],
    it: [
        {
        It: [
        'it/presentation', 'it/resilio',
        {
            Scripts: [
                {
                    type: 'autogenerated',
                    dirName: 'it/scripts'
                }
            ]
        }
    ]
}
    ],
};
